"""
ENG1013 Traffic System Project
Integrated implementation for Subsystem 1 and Subsystem 2.

Subsystem 1 chosen features:
    1.R1 - Print US1 over-height alert with detected height and date/time.
    1.R2 - US1 makes TL1 yellow for 1s, then red for 30s, then green.
    1.R3 - US2 controls TL1/TL2 depending on whether US1 saw the same vehicle.
    1.R4 - Ask the user for the over-height limit, defaulting to 4.0 m.
    1.G1 - WL1 yellow LEDs alternate while TL1 or TL2 is not green.
    1.G4 - US1 and US2 are filtered using moving averages.

Subsystem 2 chosen features:
    2.R1 - Pedestrian button sequence for TL4/TL5 and PL1/PL2.
    2.R2 - Print each pedestrian request once.
    2.R3 - TL4/TL5 normal 20s/10s cycle.
    2.G1 - 30s lockout after a successful pedestrian request.
    2.G2 - PL red flashing is generated by a hardware 555 timer.
    2.G3 - DS2 changes TL4/TL5 timing at night.
    2.I1 - US5 from subsystem 3 forces TL4/TL5 red and PL1/PL2 green.

Important:
    This file includes the US5 input required for 2.I1, but it does not
    implement the rest of subsystem 3, such as TL6, DS1, FL1 or FL2.
"""

from pymata4 import pymata4
import time


# ---------------------------------------------------------------------------
# Arduino direct pins
# ---------------------------------------------------------------------------

# Three 74HC595 shift registers are used for all LED and 555-enable outputs.
shiftDataPin = 2
shiftLatchPin = 3
shiftClockPin = 4

# Ultrasonic sensors for subsystem 1.
us1TriggerPin = 5
us1EchoPin = 6
us2TriggerPin = 7
us2EchoPin = 8

# Pedestrian buttons for subsystem 2. They are wired active-low.
pb1Pin = 9
pb2Pin = 10

# US5 is only used here as the integration signal required by 2.I1.
us5TriggerPin = 11
us5EchoPin = 12

# DS2 is the LDR for day/night timing in subsystem 2. A0 is pin 0 in Pymata4.
ds2AnalogPin = 0


# ---------------------------------------------------------------------------
# Shift-register output numbers
# ---------------------------------------------------------------------------

# Register A, nearest to the Arduino: outputs 0-7.
tl1RedOutput = 0
tl1YellowOutput = 1
tl1GreenOutput = 2
tl2RedOutput = 3
tl2YellowOutput = 4
tl2GreenOutput = 5
wl1LeftOutput = 6
wl1RightOutput = 7

# Register B: outputs 8-15.
tl4RedOutput = 8
tl4YellowOutput = 9
tl4GreenOutput = 10
tl5RedOutput = 11
tl5YellowOutput = 12
tl5GreenOutput = 13
plRedSolidOutput = 14
plGreenOutput = 15

# Register C: outputs 16-23.
plRedFlashEnableOutput = 16


# ---------------------------------------------------------------------------
# Calibration values
# ---------------------------------------------------------------------------

# Set this to the distance from US1/US2 to the road surface when no vehicle is
# under the sensor. The code scales vehicle height from this distance.
heightSensorRoadDistanceCm = 50.0
heightSensorMountHeightM = 5.0
overheightClearMarginM = 0.2

# If US1 detects a vehicle and US2 detects one within this time, the code
# treats it as the same vehicle travelling from US1 to US2.
sameVehicleWindowSeconds = 45.0

# Moving average settings for noisy ultrasonic feeds.
usMovingAverageWindow = 5
usMaxValidDistanceCm = 300.0

# US5 only detects presence at the over-height exit. These values match the
# previous subsystem 3 style of trigger/clear hysteresis.
us5TriggerDistanceCm = 15.0
us5ClearDistanceCm = 18.0

# With the wiring guide's DS2 voltage divider, darker light gives a lower A0.
ds2NightThreshold = 600


# ---------------------------------------------------------------------------
# Timing values
# ---------------------------------------------------------------------------

tl1Tl2YellowSeconds = 1.0
tl1Tl2RedSeconds = 30.0
wl1FlashFrequencyHz = 4.0
wl1FlashHalfPeriodSeconds = 1.0 / (wl1FlashFrequencyHz * 2.0)

tl4GreenDaySeconds = 20.0
tl4GreenNightSeconds = 30.0
tl5GreenDaySeconds = 10.0
tl5GreenNightSeconds = 5.0
tl4Tl5YellowSeconds = 3.0

pedestrianStartDelaySeconds = 2.0
pedestrianGreenSeconds = 3.0
pedestrianFlashRedSeconds = 2.0
pedestrianLockoutSeconds = 30.0

loopDelaySeconds = 0.05


# ---------------------------------------------------------------------------
# Global runtime state
# ---------------------------------------------------------------------------

board = None
overheightLimitM = 4.0

shiftRegisterState = [0] * 24

us1Samples = []
us2Samples = []
us5Samples = []

us1WasOverheight = 0
us2WasOverheight = 0
us5WasPresent = 0
lastUs1DetectionTime = None

tl1Colour = "green"
tl2Colour = "green"
tl4Colour = "green"
tl5Colour = "red"

tl1SequenceState = "idle"
tl2SequenceState = "idle"
tl1SequenceEndTime = 0.0
tl2SequenceEndTime = 0.0

wl1FlashState = 0
wl1NextToggleTime = 0.0

s2CycleState = "tl4Green"
s2CycleEndTime = 0.0
lastDs2NightState = -1

lastButtonPressed = 0
pedestrianState = "idle"
pedestrianEndTime = 0.0
pedestrianRoadToStop = ""
pedestrianLockoutUntil = 0.0

us5IntegrationState = "idle"
us5IntegrationEndTime = 0.0


def prompt_overheight_limit():
    """
    Ask for the 1.R4 height limit. Empty input uses the 4.0 m default.
    """
    userInput = input("Enter over-height limit in metres [default 4.0]: ").strip()

    if userInput == "":
        return 4.0

    try:
        enteredLimit = float(userInput)
    except ValueError:
        print("Invalid input. Using default over-height limit of 4.0 m.")
        return 4.0

    if enteredLimit <= 0:
        print("Limit must be positive. Using default over-height limit of 4.0 m.")
        return 4.0

    return enteredLimit


def setup_board():
    """
    Connect to the Arduino and configure all direct pins.
    """
    global board

    board = pymata4.Pymata4()

    board.set_pin_mode_digital_output(shiftDataPin)
    board.set_pin_mode_digital_output(shiftLatchPin)
    board.set_pin_mode_digital_output(shiftClockPin)

    board.set_pin_mode_sonar(us1TriggerPin, us1EchoPin)
    board.set_pin_mode_sonar(us2TriggerPin, us2EchoPin)
    board.set_pin_mode_sonar(us5TriggerPin, us5EchoPin)

    board.set_pin_mode_digital_input_pullup(pb1Pin)
    board.set_pin_mode_digital_input_pullup(pb2Pin)
    board.set_pin_mode_analog_input(ds2AnalogPin)

    time.sleep(1.0)
    all_shift_outputs_off()
    initialise_default_lights()


def write_shift_registers():
    """
    Send the 24 output states to the three daisy-chained 74HC595 registers.

    Register A is nearest to the Arduino and uses output numbers 0-7.
    Register B uses 8-15. Register C uses 16-23.
    """
    board.digital_write(shiftLatchPin, 0)

    for byteNumber in [2, 1, 0]:
        byteValue = 0

        for bitNumber in range(8):
            outputIndex = byteNumber * 8 + bitNumber
            if shiftRegisterState[outputIndex] == 1:
                byteValue = byteValue | (1 << bitNumber)

        for bitNumber in range(7, -1, -1):
            board.digital_write(shiftClockPin, 0)
            board.digital_write(shiftDataPin, 1 if (byteValue & (1 << bitNumber)) else 0)
            board.digital_write(shiftClockPin, 1)

    board.digital_write(shiftLatchPin, 1)


def set_outputs(outputPairs):
    """
    Change multiple shift-register outputs at once.
    """
    changed = 0

    for outputIndex, value in outputPairs:
        newValue = 1 if value else 0

        if shiftRegisterState[outputIndex] != newValue:
            shiftRegisterState[outputIndex] = newValue
            changed = 1

    if changed == 1:
        write_shift_registers()


def all_shift_outputs_off():
    """
    Turn off every shift-register output.
    """
    for outputIndex in range(len(shiftRegisterState)):
        shiftRegisterState[outputIndex] = 0

    write_shift_registers()


def set_tl1_colour(colour):
    """
    Set TL1 to exactly one colour.
    """
    global tl1Colour

    set_outputs([
        (tl1RedOutput, colour == "red"),
        (tl1YellowOutput, colour == "yellow"),
        (tl1GreenOutput, colour == "green"),
    ])
    tl1Colour = colour


def set_tl2_colour(colour):
    """
    Set TL2 to exactly one colour.
    """
    global tl2Colour

    set_outputs([
        (tl2RedOutput, colour == "red"),
        (tl2YellowOutput, colour == "yellow"),
        (tl2GreenOutput, colour == "green"),
    ])
    tl2Colour = colour


def set_tl4_colour(colour):
    """
    Set TL4 to exactly one colour.
    """
    global tl4Colour

    set_outputs([
        (tl4RedOutput, colour == "red"),
        (tl4YellowOutput, colour == "yellow"),
        (tl4GreenOutput, colour == "green"),
    ])
    tl4Colour = colour


def set_tl5_colour(colour):
    """
    Set TL5 to exactly one colour.
    """
    global tl5Colour

    set_outputs([
        (tl5RedOutput, colour == "red"),
        (tl5YellowOutput, colour == "yellow"),
        (tl5GreenOutput, colour == "green"),
    ])
    tl5Colour = colour


def set_pedestrian_solid_red():
    """
    Set PL1/PL2 to solid red. The 555 flash path is disabled.
    """
    set_outputs([
        (plRedSolidOutput, 1),
        (plGreenOutput, 0),
        (plRedFlashEnableOutput, 0),
    ])


def set_pedestrian_green():
    """
    Set PL1/PL2 to green. Both red paths are off.
    """
    set_outputs([
        (plRedSolidOutput, 0),
        (plGreenOutput, 1),
        (plRedFlashEnableOutput, 0),
    ])


def set_pedestrian_flashing_red():
    """
    Enable the external 555 timer so it flashes PL1/PL2 red.
    """
    set_outputs([
        (plRedSolidOutput, 0),
        (plGreenOutput, 0),
        (plRedFlashEnableOutput, 1),
    ])


def initialise_default_lights():
    """
    Put both subsystems into their normal starting states.
    """
    global s2CycleState
    global s2CycleEndTime

    set_tl1_colour("green")
    set_tl2_colour("green")
    set_outputs([(wl1LeftOutput, 0), (wl1RightOutput, 0)])

    set_pedestrian_solid_red()
    isNight, ldrValue = read_ds2_night_state()
    start_s2_cycle_state("tl4Green", time.time(), isNight)
    s2CycleState = "tl4Green"

    print("Integrated subsystem 1 + 2 started.")
    print("Over-height limit:", overheightLimitM, "m")
    print("DS2 initial A0:", ldrValue)
    print("Press Ctrl+C to stop cleanly.")


def read_filtered_distance(triggerPin, sampleList):
    """
    Read one ultrasonic sensor and return a moving average distance in cm.
    """
    reading = board.sonar_read(triggerPin)

    if reading is None or reading[0] is None:
        return None

    distanceCm = reading[0]

    if distanceCm <= 0 or distanceCm > usMaxValidDistanceCm:
        return None

    sampleList.append(distanceCm)

    if len(sampleList) > usMovingAverageWindow:
        sampleList.pop(0)

    total = 0.0
    count = 0

    for sample in sampleList:
        total = total + sample
        count = count + 1

    if count == 0:
        return None

    return total / count


def distance_to_vehicle_height(distanceCm):
    """
    Convert a model distance reading into a real-world vehicle height estimate.

    Example: if the sensor is 50 cm above the model road and represents 5 m in
    the real system, a 10 cm reading means roughly a 4 m tall vehicle.
    """
    if distanceCm is None:
        return None

    heightM = heightSensorMountHeightM * (heightSensorRoadDistanceCm - distanceCm)
    heightM = heightM / heightSensorRoadDistanceCm

    if heightM < 0:
        heightM = 0.0

    return heightM


def update_overheight_state(wasOverheight, heightM):
    """
    Apply hysteresis to avoid rapid on/off detection near the height limit.
    """
    if heightM is None:
        return 0

    if wasOverheight == 1:
        if heightM >= overheightLimitM - overheightClearMarginM:
            return 1
        return 0

    if heightM >= overheightLimitM:
        return 1

    return 0


def update_us5_presence_state(wasPresent, distanceCm):
    """
    Detect whether US5 sees a vehicle in the exit lane for 2.I1.
    """
    if distanceCm is None:
        return 0

    if wasPresent == 1:
        if distanceCm <= us5ClearDistanceCm:
            return 1
        return 0

    if distanceCm <= us5TriggerDistanceCm:
        return 1

    return 0


def read_ds2_night_state():
    """
    Return whether DS2 currently indicates night.
    """
    reading = board.analog_read(ds2AnalogPin)

    if reading is None or reading[0] is None:
        return 0, 0

    ldrValue = reading[0]

    if ldrValue <= ds2NightThreshold:
        return 1, ldrValue

    return 0, ldrValue


def print_us1_alert(heightM):
    """
    Print the 1.R1 alert once when US1 detects a new over-height vehicle.
    """
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    print("1.R1 ALERT:", timestamp, "- US1 detected over-height vehicle.")
    print("Detected height:", round(heightM, 2), "m")


def start_tl1_sequence(now):
    """
    Start the 1.R2 TL1 yellow -> red -> green sequence.
    """
    global tl1SequenceState
    global tl1SequenceEndTime

    if tl1SequenceState != "idle":
        return

    set_tl1_colour("yellow")
    tl1SequenceState = "yellow"
    tl1SequenceEndTime = now + tl1Tl2YellowSeconds
    print("TL1 -> YELLOW for 1 second")


def start_tl2_sequence(now):
    """
    Start the TL2 yellow -> red -> green sequence used by 1.R3.
    """
    global tl2SequenceState
    global tl2SequenceEndTime

    if tl2SequenceState != "idle":
        return

    set_tl2_colour("yellow")
    tl2SequenceState = "yellow"
    tl2SequenceEndTime = now + tl1Tl2YellowSeconds
    print("TL2 -> YELLOW for 1 second")


def update_tl1_tl2_sequences(now):
    """
    Continue any active TL1/TL2 timing sequences without blocking subsystem 2.
    """
    global tl1SequenceState
    global tl2SequenceState
    global tl1SequenceEndTime
    global tl2SequenceEndTime

    if tl1SequenceState == "yellow" and now >= tl1SequenceEndTime:
        set_tl1_colour("red")
        tl1SequenceState = "red"
        tl1SequenceEndTime = now + tl1Tl2RedSeconds
        print("TL1 -> RED for 30 seconds")
    elif tl1SequenceState == "red" and now >= tl1SequenceEndTime:
        set_tl1_colour("green")
        tl1SequenceState = "idle"
        print("TL1 -> GREEN")

    if tl2SequenceState == "yellow" and now >= tl2SequenceEndTime:
        set_tl2_colour("red")
        tl2SequenceState = "red"
        tl2SequenceEndTime = now + tl1Tl2RedSeconds
        print("TL2 -> RED for 30 seconds")
    elif tl2SequenceState == "red" and now >= tl2SequenceEndTime:
        set_tl2_colour("green")
        tl2SequenceState = "idle"
        print("TL2 -> GREEN")


def update_wl1(now):
    """
    Flash WL1 while either TL1 or TL2 is not green.
    """
    global wl1FlashState
    global wl1NextToggleTime

    if tl1Colour == "green" and tl2Colour == "green":
        set_outputs([(wl1LeftOutput, 0), (wl1RightOutput, 0)])
        return

    if now >= wl1NextToggleTime:
        wl1FlashState = 1 - wl1FlashState
        wl1NextToggleTime = now + wl1FlashHalfPeriodSeconds

        set_outputs([
            (wl1LeftOutput, wl1FlashState == 1),
            (wl1RightOutput, wl1FlashState == 0),
        ])


def update_subsystem1(now):
    """
    Read US1/US2 and trigger subsystem 1 behaviour when new detections occur.
    """
    global us1WasOverheight
    global us2WasOverheight
    global lastUs1DetectionTime

    us1DistanceCm = read_filtered_distance(us1TriggerPin, us1Samples)
    us2DistanceCm = read_filtered_distance(us2TriggerPin, us2Samples)

    us1HeightM = distance_to_vehicle_height(us1DistanceCm)
    us2HeightM = distance_to_vehicle_height(us2DistanceCm)

    us1IsOverheight = update_overheight_state(us1WasOverheight, us1HeightM)
    us2IsOverheight = update_overheight_state(us2WasOverheight, us2HeightM)

    if us1IsOverheight == 1 and us1WasOverheight == 0:
        lastUs1DetectionTime = now
        print_us1_alert(us1HeightM)
        start_tl1_sequence(now)

    if us2IsOverheight == 1 and us2WasOverheight == 0:
        sameVehicle = 0

        if lastUs1DetectionTime is not None:
            if now - lastUs1DetectionTime <= sameVehicleWindowSeconds:
                sameVehicle = 1

        if sameVehicle == 1:
            print("1.R3: US2 detected the same over-height vehicle as US1.")
            start_tl2_sequence(now)
        else:
            print("1.R3: US2 detected an over-height vehicle without recent US1 detection.")
            start_tl1_sequence(now)
            start_tl2_sequence(now)

    us1WasOverheight = us1IsOverheight
    us2WasOverheight = us2IsOverheight

    update_tl1_tl2_sequences(now)
    update_wl1(now)


def get_tl4_green_seconds(isNight):
    """
    Return the current TL4 green duration based on DS2.
    """
    if isNight == 1:
        return tl4GreenNightSeconds

    return tl4GreenDaySeconds


def get_tl5_green_seconds(isNight):
    """
    Return the current TL5 green duration based on DS2.
    """
    if isNight == 1:
        return tl5GreenNightSeconds

    return tl5GreenDaySeconds


def start_s2_cycle_state(newState, now, isNight):
    """
    Start one state in the normal TL4/TL5 2.R3 cycle.
    """
    global s2CycleState
    global s2CycleEndTime

    s2CycleState = newState

    if newState == "tl4Green":
        set_tl4_colour("green")
        set_tl5_colour("red")
        s2CycleEndTime = now + get_tl4_green_seconds(isNight)
    elif newState == "tl4Yellow":
        set_tl4_colour("yellow")
        set_tl5_colour("red")
        s2CycleEndTime = now + tl4Tl5YellowSeconds
    elif newState == "tl5Green":
        set_tl4_colour("red")
        set_tl5_colour("green")
        s2CycleEndTime = now + get_tl5_green_seconds(isNight)
    elif newState == "tl5Yellow":
        set_tl4_colour("red")
        set_tl5_colour("yellow")
        s2CycleEndTime = now + tl4Tl5YellowSeconds


def update_s2_normal_cycle(now, isNight):
    """
    Continue the normal 2.R3 TL4/TL5 cycle.
    """
    if now < s2CycleEndTime:
        return

    if s2CycleState == "tl4Green":
        start_s2_cycle_state("tl4Yellow", now, isNight)
    elif s2CycleState == "tl4Yellow":
        start_s2_cycle_state("tl5Green", now, isNight)
    elif s2CycleState == "tl5Green":
        start_s2_cycle_state("tl5Yellow", now, isNight)
    elif s2CycleState == "tl5Yellow":
        start_s2_cycle_state("tl4Green", now, isNight)


def log_ds2_change(isNight, ldrValue):
    """
    Print DS2 day/night changes only once per change.
    """
    global lastDs2NightState

    if isNight != lastDs2NightState:
        if isNight == 1:
            print("2.G3: DS2 NIGHT mode. A0 =", ldrValue)
        else:
            print("2.G3: DS2 DAY mode. A0 =", ldrValue)

        lastDs2NightState = isNight


def read_button_pressed():
    """
    Read PB1/PB2. Buttons are active-low because inputs use pull-ups.
    """
    pb1Reading = board.digital_read(pb1Pin)
    pb2Reading = board.digital_read(pb2Pin)

    pb1Value = 1
    pb2Value = 1

    if pb1Reading is not None and pb1Reading[0] is not None:
        pb1Value = pb1Reading[0]

    if pb2Reading is not None and pb2Reading[0] is not None:
        pb2Value = pb2Reading[0]

    if pb1Value == 0 or pb2Value == 0:
        return 1

    return 0


def start_pedestrian_sequence(now):
    """
    Start the 2.R1 pedestrian sequence after a valid button request.
    """
    global pedestrianState
    global pedestrianEndTime

    pedestrianState = "waitBeforeRoadStop"
    pedestrianEndTime = now + pedestrianStartDelaySeconds
    print("2.R2: pedestrian request accepted. Sequence will start after 2 seconds.")


def update_pedestrian_button(now):
    """
    Queue one pedestrian sequence when PB1/PB2 is pressed and lockout has passed.
    """
    global lastButtonPressed

    buttonPressed = read_button_pressed()

    if buttonPressed == 1 and lastButtonPressed == 0:
        if pedestrianState == "idle" and now >= pedestrianLockoutUntil:
            start_pedestrian_sequence(now)
        elif now < pedestrianLockoutUntil:
            remaining = int(pedestrianLockoutUntil - now)
            print("2.G1: pedestrian request ignored during lockout. Remaining:", remaining, "s")

    lastButtonPressed = buttonPressed


def update_pedestrian_sequence(now, isNight):
    """
    Continue the 2.R1 pedestrian sequence.
    """
    global pedestrianState
    global pedestrianEndTime
    global pedestrianRoadToStop
    global pedestrianLockoutUntil

    if pedestrianState == "idle" or now < pedestrianEndTime:
        return

    if pedestrianState == "waitBeforeRoadStop":
        if tl5Colour != "red":
            pedestrianRoadToStop = "tl5"
            set_tl5_colour("yellow")
            print("2.R1: TL5 -> YELLOW for 3 seconds")
        else:
            pedestrianRoadToStop = "tl4"
            set_tl4_colour("yellow")
            print("2.R1: TL4 -> YELLOW for 3 seconds")

        pedestrianState = "roadYellow"
        pedestrianEndTime = now + tl4Tl5YellowSeconds

    elif pedestrianState == "roadYellow":
        if pedestrianRoadToStop == "tl5":
            set_tl5_colour("red")
        else:
            set_tl4_colour("red")

        set_tl4_colour("red")
        set_tl5_colour("red")
        set_pedestrian_green()
        pedestrianState = "pedestrianGreen"
        pedestrianEndTime = now + pedestrianGreenSeconds
        print("2.R1: PL1/PL2 -> GREEN for 3 seconds")

    elif pedestrianState == "pedestrianGreen":
        set_pedestrian_flashing_red()
        pedestrianState = "pedestrianFlashRed"
        pedestrianEndTime = now + pedestrianFlashRedSeconds
        print("2.G2: PL1/PL2 -> FLASHING RED from 555 timer for 2 seconds")

    elif pedestrianState == "pedestrianFlashRed":
        set_pedestrian_solid_red()
        start_s2_cycle_state("tl4Green", now, isNight)
        pedestrianLockoutUntil = now + pedestrianLockoutSeconds
        pedestrianState = "idle"
        print("2.R1: PL1/PL2 -> SOLID RED. TL4 -> GREEN.")
        print("2.G1: 30 second pedestrian lockout started.")


def start_us5_integration(now):
    """
    Start 2.I1 when US5 detects an over-height vehicle exiting.
    """
    global pedestrianState
    global us5IntegrationState
    global us5IntegrationEndTime

    pedestrianState = "idle"
    set_pedestrian_solid_red()

    if tl4Colour != "red":
        set_tl4_colour("yellow")
        us5IntegrationState = "stoppingTl4"
        us5IntegrationEndTime = now + tl4Tl5YellowSeconds
        print("2.I1: US5 detected vehicle. TL4 -> YELLOW for 3 seconds.")
    elif tl5Colour != "red":
        set_tl5_colour("yellow")
        us5IntegrationState = "stoppingTl5"
        us5IntegrationEndTime = now + tl4Tl5YellowSeconds
        print("2.I1: US5 detected vehicle. TL5 -> YELLOW for 3 seconds.")
    else:
        set_pedestrian_green()
        us5IntegrationState = "pedestrianGreen"
        print("2.I1: TL4/TL5 already red. PL1/PL2 -> GREEN.")


def update_us5_integration(now, us5Present, isNight):
    """
    Continue the 2.I1 override sequence.
    """
    global us5IntegrationState
    global us5IntegrationEndTime

    if us5IntegrationState == "idle":
        return

    if us5IntegrationState == "stoppingTl4":
        if now < us5IntegrationEndTime:
            return

        set_tl4_colour("red")

        if tl5Colour != "red":
            set_tl5_colour("yellow")
            us5IntegrationState = "stoppingTl5"
            us5IntegrationEndTime = now + tl4Tl5YellowSeconds
            print("2.I1: TL5 -> YELLOW for 3 seconds.")
        else:
            set_pedestrian_green()
            us5IntegrationState = "pedestrianGreen"
            print("2.I1: PL1/PL2 -> GREEN while US5 detects vehicle.")

    elif us5IntegrationState == "stoppingTl5":
        if now < us5IntegrationEndTime:
            return

        set_tl5_colour("red")
        set_pedestrian_green()
        us5IntegrationState = "pedestrianGreen"
        print("2.I1: PL1/PL2 -> GREEN while US5 detects vehicle.")

    elif us5IntegrationState == "pedestrianGreen":
        set_tl4_colour("red")
        set_tl5_colour("red")
        set_pedestrian_green()

        if us5Present == 0:
            set_pedestrian_flashing_red()
            us5IntegrationState = "pedestrianFlashRed"
            us5IntegrationEndTime = now + pedestrianFlashRedSeconds
            print("2.I1: US5 clear. PL1/PL2 -> FLASHING RED for 2 seconds.")

    elif us5IntegrationState == "pedestrianFlashRed":
        if now < us5IntegrationEndTime:
            return

        set_pedestrian_solid_red()
        start_s2_cycle_state("tl4Green", now, isNight)
        us5IntegrationState = "idle"
        print("2.I1: PL1/PL2 -> SOLID RED. Normal 2.R3 cycle resumed at TL4 green.")


def update_subsystem2(now):
    """
    Read DS2, PB1/PB2 and US5, then run subsystem 2 behaviour.
    """
    global us5WasPresent

    isNight, ldrValue = read_ds2_night_state()
    log_ds2_change(isNight, ldrValue)

    us5DistanceCm = read_filtered_distance(us5TriggerPin, us5Samples)
    us5Present = update_us5_presence_state(us5WasPresent, us5DistanceCm)

    if us5Present == 1 and us5WasPresent == 0 and us5IntegrationState == "idle":
        start_us5_integration(now)

    us5WasPresent = us5Present

    if us5IntegrationState != "idle":
        update_us5_integration(now, us5Present, isNight)
        return

    update_pedestrian_button(now)

    if pedestrianState != "idle":
        update_pedestrian_sequence(now, isNight)
        return

    update_s2_normal_cycle(now, isNight)


def shutdown_system():
    """
    Turn off outputs and close the Arduino connection cleanly.
    """
    global board

    if board is None:
        return

    all_shift_outputs_off()
    time.sleep(0.2)
    board.shutdown()
    board = None


def main():
    """
    Run subsystem 1 and subsystem 2 together on one Arduino.
    """
    global overheightLimitM

    overheightLimitM = prompt_overheight_limit()
    setup_board()

    try:
        while True:
            now = time.time()
            update_subsystem1(now)
            update_subsystem2(now)
            time.sleep(loopDelaySeconds)

    except KeyboardInterrupt:
        print("\nKeyboardInterrupt received. Shutting down integrated system.")
    finally:
        shutdown_system()


if __name__ == "__main__":
    main()
