"""
ENG1013 Traffic System Project
Integrated code for Subsystem 2 and Subsystem 3 on one Arduino UNO (partial integration).

This file is a combination of both the individual subsystem standalone code that we created:

Included Subsystem 2 features:
    2.R1, 2.R2, 2.R3, 2.G1, 2.G3, 2.I1

Included Subsystem 3 features:
    3.R1, 3.R2, 3.G2, 3.G3, 3.G4, 3.I1

Excluded features (due to point cap):
    2.G2 - PL1/PL2 flashing red frequency generated by a 555 timer.
           This version flashes PL1/PL2 red in software instead.
    3.G1 - TL6 flashing green using a 555 timer.
"""

from pymata4 import pymata4
import time


# ============================================================
# Board connection
# ============================================================

# Set this to a COM port string like "COM4" if auto-detection does not work.
BOARD_COM_PORT = None


# ============================================================
# Pin assignments from test_sub2_standalone.py
# ============================================================

PB1_PIN = 12
PB2_PIN = 13
DS2_PIN = 1      # A1

SRCLK_PIN = 19   # A5
RCLK_PIN = 18    # A4
SER_PIN = 17     # A3

# PL1/PL2 red is directly connected to Arduino D2.
# This replaces the excluded 2.G2 hardware 555 timer feature.
PL12_RED_PIN = 2


# ============================================================
# Pin assignments from Final Subsystem 3 CODE.py
# ============================================================

US5_TRIGGER_PIN = 6
US5_ECHO_PIN = 7

TL6_RED_PIN = 8
TL6_YELLOW_PIN = 9
TL6_GREEN_PIN = 10

FL1_PIN = 11
FL2_PIN = 5

DS1_ANALOG_PIN = 0  # A0


# ============================================================
# Subsystem 2 shift register bit positions.
# PL1/PL2 red is not on the shift register in this version; it uses D2.
# ============================================================

SR_UNUSED_0 = 0
SR_PL12_GRN = 1
SR_TL5_GRN = 2
SR_TL5_YLW = 3
SR_TL5_RED = 4
SR_TL4_GRN = 5
SR_TL4_YLW = 6
SR_TL4_RED = 7
SR_LENGTH = 8


# ============================================================
# Timing constants
# ============================================================

# Subsystem 2 timings
YELLOW_TIME = 3.0
PED_GREEN_TIME = 3.0
PED_FLASH_TIME = 2.0
PED_WAIT = 2.0
PED_LOCKOUT = 30.0
TL4_GREEN_DAY = 20.0
TL4_GREEN_NIGHT = 30.0
TL5_GREEN_DAY = 10.0
TL5_GREEN_NIGHT = 5.0
PL12_FLASH_HALF_PERIOD = 0.25  # 2 Hz software flashing

# Subsystem 3 timings
DAY_GREEN_SECONDS = 5.0
NIGHT_GREEN_SECONDS = 10.0
TL6_YELLOW_SECONDS = 3.0
MINIMUM_TL6_RELEASE_DELAY = 3.0

POLL_DELAY_SECONDS = 0.05


# ============================================================
# Sensor calibration
# ============================================================

# LDR calibration for DS1 and DS2.
# These are separate because DS1 and DS2 may be wired with opposite voltage
# divider directions. Set a sensor to False if shining a torch makes its
# analog value go up.
DS1_BRIGHT_READING_IS_LOW = True
DS2_BRIGHT_READING_IS_LOW = False

# Subsystem 2 LDR boundaries. DS2 is currently reading much lower than DS1.
# Because DS2 is wired so higher readings mean brighter light, it changes to
# day only when a flashlight pushes it above 400. It returns to night below 320.
DS_NIGHT_BOUNDARY = 400
DS_DAY_BOUNDARY = 320

# Subsystem 3 LDR boundaries.
NIGHT_LDR_THRESHOLD = 550
DS1_DAY_THRESHOLD = 300

# Smooth the LDR readings so brief LED glare does not cause timing glitches.
LDR_FILTER_ALPHA = 0.20

# US5 moving-average filtering and vehicle detection.
EXIT_LANE_TRIGGER_DISTANCE_CM = 15.0
EXIT_LANE_CLEAR_DISTANCE_CM = 18.0
US5_MOVING_AVERAGE_WINDOW = 5
US5_MAX_VALID_DISTANCE_CM = 300.0


# ============================================================
# Subsystem 2 mode names
# ============================================================

MODE_TL4_GREEN = "TL4_GREEN"
MODE_TL5_GREEN = "TL5_GREEN"
MODE_YELLOW = "YELLOW"
MODE_PED_WAIT = "PED_WAIT"
MODE_PED_WALK = "PED_WALK"
MODE_PED_FLASH = "PED_FLASH"
MODE_EMERG_HOLD = "EMERG_HOLD"
MODE_EMERG_FLASH = "EMERG_FLASH"


# ============================================================
# Global runtime state
# ============================================================

board = None

state = {
    "shiftRegBits": [0] * SR_LENGTH,
    "lastShiftRegBits": [0] * SR_LENGTH,
    "DS2nightTime": False,
    "sub2Mode": MODE_TL4_GREEN,
    "sub2ModeStartTime": 0.0,
    "sub2GreenDuration": TL4_GREEN_DAY,
    "sub2YellowWhich": "TL4",
    "sub2YellowAfter": MODE_TL5_GREEN,
    "sub2PedRequestPending": False,
    "sub2PedRequestTime": 0.0,
    "sub2PBwasPressed": False,
    "sub2OverheightDetected": False,
    "sub2Lockout": False,
    "sub2LockoutStartTime": 0.0,
    "sub2EmergencyStartTime": 0.0,
    "sub2EmergencyQueuedPrinted": False,
    "sub2WaitingForTL6RedPrinted": False,
}

PL12RedState = {"flashing": False, "lastToggleTime": 0.0, "redOutput": 0}

ldr_state = {
    "DS1Filtered": None,
    "DS1nightTime": False,
    "DS2Filtered": None,
}

us5_samples = []
last_us5_present = 0

sub3_mode = "RED_IDLE"
sub3_mode_start_time = 0.0
sub3_green_time = DAY_GREEN_SECONDS

last_ds1_state = -1


# ============================================================
# Board setup and shutdown
# ============================================================

def setup_board():
    """Connect to the Arduino and configure every Subsystem 2 and 3 pin."""
    global board

    if BOARD_COM_PORT is None:
        board = pymata4.Pymata4()
    else:
        board = pymata4.Pymata4(com_port=BOARD_COM_PORT)

    # Subsystem 2 outputs and inputs
    board.set_pin_mode_digital_output(SRCLK_PIN)
    board.set_pin_mode_digital_output(RCLK_PIN)
    board.set_pin_mode_digital_output(SER_PIN)
    board.set_pin_mode_digital_output(PL12_RED_PIN)
    board.set_pin_mode_digital_input(PB1_PIN)
    board.set_pin_mode_digital_input(PB2_PIN)
    board.set_pin_mode_analog_input(DS2_PIN)

    # Subsystem 3 outputs and inputs
    board.set_pin_mode_digital_output(TL6_RED_PIN)
    board.set_pin_mode_digital_output(TL6_YELLOW_PIN)
    board.set_pin_mode_digital_output(TL6_GREEN_PIN)
    board.set_pin_mode_digital_output(FL1_PIN)
    board.set_pin_mode_digital_output(FL2_PIN)
    board.set_pin_mode_analog_input(DS1_ANALOG_PIN)
    board.set_pin_mode_sonar(US5_TRIGGER_PIN, US5_ECHO_PIN)

    time.sleep(1.0)

    setup_initial_outputs()


def setup_initial_outputs():
    """Set the starting state: TL4 green, TL5 red, PL solid red, TL6 red."""
    state["shiftRegBits"] = [0] * SR_LENGTH
    state["lastShiftRegBits"] = [1] * SR_LENGTH

    TL4_green()
    TL5_red()
    PL12_green_off()
    PL12_solid_red_on()
    shift_out_bits()

    set_tl6_red()
    set_floodlights(0)

    state["sub2Mode"] = MODE_TL4_GREEN
    state["sub2ModeStartTime"] = time.time()
    state["sub2GreenDuration"] = TL4_GREEN_DAY

    print("Integrated Subsystem 2 + Subsystem 3 started.")
    if DS1_BRIGHT_READING_IS_LOW:
        print("DS1 mode: low analog reading = bright/day.")
    else:
        print("DS1 mode: high analog reading = bright/day.")
    if DS2_BRIGHT_READING_IS_LOW:
        print("DS2 mode: low analog reading = bright/day.")
    else:
        print("DS2 mode: high analog reading = bright/day.")
    if DS2_BRIGHT_READING_IS_LOW:
        print("DS2 Thresholds: night >=", DS_NIGHT_BOUNDARY, "day <=", DS_DAY_BOUNDARY)
    else:
        print("DS2 Thresholds: day >=", DS_NIGHT_BOUNDARY, "night <=", DS_DAY_BOUNDARY)
    if DS1_BRIGHT_READING_IS_LOW:
        print("DS1 Thresholds: night >=", NIGHT_LDR_THRESHOLD, "day <=", DS1_DAY_THRESHOLD)
    else:
        print("DS1 Thresholds: day >=", NIGHT_LDR_THRESHOLD, "night <=", DS1_DAY_THRESHOLD)
    print("Press Ctrl+C to stop.")


def shutdown_system():
    """Turn all outputs off before closing the Arduino connection."""
    global board

    if board is None:
        return

    try:
        state["shiftRegBits"] = [0] * SR_LENGTH
        state["lastShiftRegBits"] = [1] * SR_LENGTH
        shift_out_bits()
        board.digital_write(PL12_RED_PIN, 0)
        set_tl6_all_off()
        set_floodlights(0)
        time.sleep(0.2)
        board.shutdown()
    except Exception:
        pass

    board = None


# ============================================================
# Subsystem 2 shift register and light helpers
# ============================================================

def shift_out_bits():
    """Send the current Subsystem 2 LED bits to the shift register."""
    if state["shiftRegBits"] == state["lastShiftRegBits"]:
        return

    board.digital_write(SRCLK_PIN, 0)
    board.digital_write(SER_PIN, 0)
    board.digital_write(RCLK_PIN, 0)

    for i in range(SR_LENGTH):
        board.digital_write(SER_PIN, state["shiftRegBits"][i])
        board.digital_write(SRCLK_PIN, 1)
        board.digital_write(SRCLK_PIN, 0)

    board.digital_write(RCLK_PIN, 1)
    board.digital_write(RCLK_PIN, 0)

    state["lastShiftRegBits"] = state["shiftRegBits"][:]


def TL4_red():
    state["shiftRegBits"][SR_TL4_RED] = 1
    state["shiftRegBits"][SR_TL4_YLW] = 0
    state["shiftRegBits"][SR_TL4_GRN] = 0


def TL4_yellow():
    state["shiftRegBits"][SR_TL4_RED] = 0
    state["shiftRegBits"][SR_TL4_YLW] = 1
    state["shiftRegBits"][SR_TL4_GRN] = 0


def TL4_green():
    state["shiftRegBits"][SR_TL4_RED] = 0
    state["shiftRegBits"][SR_TL4_YLW] = 0
    state["shiftRegBits"][SR_TL4_GRN] = 1


def TL5_red():
    state["shiftRegBits"][SR_TL5_RED] = 1
    state["shiftRegBits"][SR_TL5_YLW] = 0
    state["shiftRegBits"][SR_TL5_GRN] = 0


def TL5_yellow():
    state["shiftRegBits"][SR_TL5_RED] = 0
    state["shiftRegBits"][SR_TL5_YLW] = 1
    state["shiftRegBits"][SR_TL5_GRN] = 0


def TL5_green():
    state["shiftRegBits"][SR_TL5_RED] = 0
    state["shiftRegBits"][SR_TL5_YLW] = 0
    state["shiftRegBits"][SR_TL5_GRN] = 1


def PL12_green_on():
    PL12RedState["flashing"] = False
    PL12RedState["redOutput"] = 0
    board.digital_write(PL12_RED_PIN, 0)
    state["shiftRegBits"][SR_PL12_GRN] = 1


def PL12_green_off():
    state["shiftRegBits"][SR_PL12_GRN] = 0


def PL12_solid_red_on():
    """Set PL1/PL2 to solid red for normal stopped pedestrians."""
    PL12RedState["flashing"] = False
    PL12RedState["redOutput"] = 1
    board.digital_write(PL12_RED_PIN, 1)
    state["shiftRegBits"][SR_PL12_GRN] = 0


def PL12_start_flash_red():
    """Start software flashing for PL1/PL2 red."""
    PL12RedState["flashing"] = True
    PL12RedState["lastToggleTime"] = time.time()
    PL12RedState["redOutput"] = 1
    board.digital_write(PL12_RED_PIN, 1)
    state["shiftRegBits"][SR_PL12_GRN] = 0


def PL12_stop_flash_red():
    """Stop flashing and return PL1/PL2 to solid red."""
    PL12_solid_red_on()


def PL12_red_update():
    """Toggle PL1/PL2 red while software flashing is active."""
    if not PL12RedState["flashing"]:
        return

    if time.time() - PL12RedState["lastToggleTime"] >= PL12_FLASH_HALF_PERIOD:
        if PL12RedState["redOutput"] == 1:
            PL12RedState["redOutput"] = 0
        else:
            PL12RedState["redOutput"] = 1

        board.digital_write(PL12_RED_PIN, PL12RedState["redOutput"])
        state["shiftRegBits"][SR_PL12_GRN] = 0
        PL12RedState["lastToggleTime"] = time.time()


# ============================================================
# Subsystem 3 output helpers
# ============================================================

def set_tl6_red():
    board.digital_write(TL6_RED_PIN, 1)
    board.digital_write(TL6_YELLOW_PIN, 0)
    board.digital_write(TL6_GREEN_PIN, 0)


def set_tl6_yellow():
    board.digital_write(TL6_RED_PIN, 0)
    board.digital_write(TL6_YELLOW_PIN, 1)
    board.digital_write(TL6_GREEN_PIN, 0)


def set_tl6_green():
    board.digital_write(TL6_RED_PIN, 0)
    board.digital_write(TL6_YELLOW_PIN, 0)
    board.digital_write(TL6_GREEN_PIN, 1)


def set_tl6_all_off():
    board.digital_write(TL6_RED_PIN, 0)
    board.digital_write(TL6_YELLOW_PIN, 0)
    board.digital_write(TL6_GREEN_PIN, 0)


def set_floodlights(state_value):
    output = 1 if state_value else 0
    board.digital_write(FL1_PIN, output)
    board.digital_write(FL2_PIN, output)


# ============================================================
# Shared sensor helpers
# ============================================================

def update_filtered_ldr(filter_key, raw_value):
    """Low-pass filter the LDR reading to reduce brief LED glare spikes."""
    old_value = ldr_state[filter_key]

    if old_value is None:
        ldr_state[filter_key] = float(raw_value)
    else:
        ldr_state[filter_key] = (
            old_value * (1.0 - LDR_FILTER_ALPHA)
            + float(raw_value) * LDR_FILTER_ALPHA
        )

    return ldr_state[filter_key]


def ldr_value_is_night(
    value,
    was_night,
    night_threshold,
    day_threshold,
    bright_reading_is_low,
):
    """Convert a filtered LDR value into night/day using hysteresis."""
    if bright_reading_is_low:
        if was_night:
            return value > day_threshold
        return value >= night_threshold

    if was_night:
        return value < night_threshold
    return value <= day_threshold


def read_daylight():
    """Read DS2 and update Subsystem 2 day/night timing mode."""
    reading = board.analog_read(DS2_PIN)

    if reading is None or reading[0] is None:
        return

    value = reading[0]
    was_night = state["DS2nightTime"]
    filtered_value = update_filtered_ldr("DS2Filtered", value)
    state["DS2nightTime"] = ldr_value_is_night(
        filtered_value,
        was_night,
        DS_NIGHT_BOUNDARY,
        DS_DAY_BOUNDARY,
        DS2_BRIGHT_READING_IS_LOW,
    )

    if state["DS2nightTime"] != was_night:
        if state["DS2nightTime"]:
            print("[SUB2] DS2 NIGHT detected. DS2 =", value)
        else:
            print("[SUB2] DS2 DAY detected. DS2 =", value)


def read_ds1_state(us5_present):
    """Read DS1. Return 1 for night and 0 for day."""
    reading = board.analog_read(DS1_ANALOG_PIN)

    if reading is None or reading[0] is None:
        if ldr_state["DS1nightTime"]:
            return 1, 0
        return 0, 0

    value = reading[0]
    filtered_value = update_filtered_ldr("DS1Filtered", value)
    was_night = ldr_state["DS1nightTime"]

    # If the event started at night, keep treating it as night until TL6 has
    # finished. This stops FL1/FL2 or nearby LEDs from fooling DS1 mid-event.
    if was_night and (us5_present == 1 or sub3_mode != "RED_IDLE"):
        return 1, value

    ldr_state["DS1nightTime"] = ldr_value_is_night(
        filtered_value,
        was_night,
        NIGHT_LDR_THRESHOLD,
        DS1_DAY_THRESHOLD,
        DS1_BRIGHT_READING_IS_LOW,
    )

    if ldr_state["DS1nightTime"]:
        return 1, value

    return 0, value


def log_ds1_change(is_night, ldr_value):
    """Print DS1 day/night changes without spamming the console."""
    global last_ds1_state

    if is_night != last_ds1_state:
        if is_night == 1:
            print("[SUB3] DS1 NIGHT detected. DS1 =", ldr_value)
        else:
            print("[SUB3] DS1 DAY detected. DS1 =", ldr_value)
        last_ds1_state = is_night


def read_us5_filtered_distance():
    """Read US5 and return a moving-average distance in centimetres."""
    reading = board.sonar_read(US5_TRIGGER_PIN)

    if reading is None or reading[0] is None:
        return None

    distance_cm = reading[0]

    if distance_cm <= 0:
        return None

    if distance_cm > US5_MAX_VALID_DISTANCE_CM:
        return None

    us5_samples.append(distance_cm)

    if len(us5_samples) > US5_MOVING_AVERAGE_WINDOW:
        us5_samples.pop(0)

    total = 0.0
    sample_count = 0

    for sample in us5_samples:
        total = total + sample
        sample_count = sample_count + 1

    if sample_count == 0:
        return None

    return total / sample_count


def calculate_us5_presence(currently_active, filtered_distance):
    """Apply trigger/clear thresholds to the filtered US5 distance."""
    if filtered_distance is None:
        return 0

    if currently_active == 1:
        if filtered_distance <= EXIT_LANE_CLEAR_DISTANCE_CM:
            return 1
        return 0

    if filtered_distance <= EXIT_LANE_TRIGGER_DISTANCE_CM:
        return 1

    return 0


# ============================================================
# Subsystem 2 state machine
# ============================================================

def enter_mode(new_mode):
    """Switch Subsystem 2 to a new mode and remember when it started."""
    state["sub2Mode"] = new_mode
    state["sub2ModeStartTime"] = time.time()

    # Lock the green duration when a phase starts. DS2 changes then apply to
    # the next phase, instead of shortening or lengthening the current one.
    if new_mode == MODE_TL4_GREEN:
        if state["DS2nightTime"]:
            state["sub2GreenDuration"] = TL4_GREEN_NIGHT
        else:
            state["sub2GreenDuration"] = TL4_GREEN_DAY
    elif new_mode == MODE_TL5_GREEN:
        if state["DS2nightTime"]:
            state["sub2GreenDuration"] = TL5_GREEN_NIGHT
        else:
            state["sub2GreenDuration"] = TL5_GREEN_DAY


def start_yellow(which_tl, after_mode):
    """Start a 3 second yellow phase on TL4 or TL5."""
    if which_tl == "TL4":
        TL4_yellow()
    else:
        TL5_yellow()

    state["sub2YellowWhich"] = which_tl
    state["sub2YellowAfter"] = after_mode
    enter_mode(MODE_YELLOW)


def start_emergency():
    """Queue the overheight response without cutting short TL4/TL5 green."""
    state["sub2PedRequestPending"] = False
    if state["sub2EmergencyStartTime"] == 0.0:
        state["sub2EmergencyStartTime"] = time.time()

    mode = state["sub2Mode"]

    if mode in (MODE_TL4_GREEN, MODE_TL5_GREEN):
        if not state["sub2EmergencyQueuedPrinted"]:
            print("[SUB2] OVERHEIGHT detected - waiting for current TL4/TL5 sequence to finish")
            state["sub2EmergencyQueuedPrinted"] = True
    elif mode == MODE_YELLOW:
        # If a yellow phase is already running, finish that one yellow phase
        # and go to the overheight hold. Do not restart or re-print each loop.
        if not state["sub2EmergencyQueuedPrinted"]:
            print("[SUB2] OVERHEIGHT detected - waiting for current yellow to finish")
            state["sub2EmergencyQueuedPrinted"] = True
        state["sub2YellowAfter"] = MODE_EMERG_HOLD
    else:
        TL4_red()
        TL5_red()
        PL12_stop_flash_red()
        PL12_green_on()
        enter_mode(MODE_EMERG_HOLD)


def do_TL4_green():
    """Normal TL4 green phase with day/night timing from DS2."""
    green_time = state["sub2GreenDuration"]
    elapsed = time.time() - state["sub2ModeStartTime"]

    if state["sub2OverheightDetected"]:
        state["sub2PedRequestPending"] = False
        if elapsed >= green_time:
            start_yellow("TL4", MODE_EMERG_HOLD)
        return

    if state["sub2PedRequestPending"]:
        if time.time() - state["sub2PedRequestTime"] >= PED_WAIT:
            start_yellow("TL4", MODE_PED_WALK)
        return

    if elapsed >= green_time:
        start_yellow("TL4", MODE_TL5_GREEN)


def do_TL5_green():
    """Normal TL5 green phase with day/night timing from DS2."""
    green_time = state["sub2GreenDuration"]
    elapsed = time.time() - state["sub2ModeStartTime"]

    if state["sub2OverheightDetected"]:
        state["sub2PedRequestPending"] = False
        if elapsed >= green_time:
            start_yellow("TL5", MODE_EMERG_HOLD)
        return

    if state["sub2PedRequestPending"]:
        if time.time() - state["sub2PedRequestTime"] >= PED_WAIT:
            start_yellow("TL5", MODE_PED_WALK)
        return

    if elapsed >= green_time:
        start_yellow("TL5", MODE_TL4_GREEN)


def do_yellow():
    """Finish the active yellow phase after 3 seconds."""
    elapsed = time.time() - state["sub2ModeStartTime"]

    if elapsed < YELLOW_TIME:
        return

    which = state["sub2YellowWhich"]

    if which == "TL4":
        TL4_red()
    else:
        TL5_red()

    next_mode = state["sub2YellowAfter"]

    if next_mode == MODE_TL4_GREEN:
        TL4_green()
        TL5_red()
    elif next_mode == MODE_TL5_GREEN:
        TL4_red()
        TL5_green()
    elif next_mode == MODE_PED_WALK:
        state["sub2PedRequestPending"] = False
        PL12_green_on()
        print("[SUB2] PL1 + PL2 GREEN (walk)")
    elif next_mode == MODE_EMERG_HOLD:
        TL4_red()
        TL5_red()
        PL12_stop_flash_red()
        PL12_green_on()
        print("[SUB2] TL4/TL5 are RED - TL6 may start after the 3s minimum delay")

    enter_mode(next_mode)


def do_ped_wait():
    """Compatibility mode only; pedestrian waiting is handled before yellow."""
    PL12_green_on()
    print("[SUB2] PL1 + PL2 GREEN (walk)")
    enter_mode(MODE_PED_WALK)


def do_ped_walk():
    """Keep PL1/PL2 green for 3 seconds."""
    elapsed = time.time() - state["sub2ModeStartTime"]

    if elapsed >= PED_GREEN_TIME:
        PL12_green_off()
        PL12_start_flash_red()
        print("[SUB2] PL1 + PL2 flashing RED (2s)")
        enter_mode(MODE_PED_FLASH)


def do_ped_flash():
    """Flash PL1/PL2 red for 2 seconds, then start the 30 second lockout."""
    elapsed = time.time() - state["sub2ModeStartTime"]

    if elapsed >= PED_FLASH_TIME:
        PL12_stop_flash_red()
        TL4_green()
        TL5_red()
        state["sub2Lockout"] = True
        state["sub2LockoutStartTime"] = time.time()
        state["sub2PedRequestPending"] = False
        print("[SUB2] Crossing complete - 30s lockout started")
        enter_mode(MODE_TL4_GREEN)


def do_emerg_hold():
    """Hold TL4/TL5 red and PL1/PL2 green while US5 detects the vehicle."""
    TL4_red()
    TL5_red()
    PL12_green_on()

    if not state["sub2OverheightDetected"]:
        PL12_green_off()
        PL12_start_flash_red()
        state["sub2WaitingForTL6RedPrinted"] = False
        print("[SUB2] Overheight cleared - PL1/PL2 flashing RED (2s)")
        enter_mode(MODE_EMERG_FLASH)


def do_emerg_flash():
    """After US5 clears, wait for TL6 red before resuming TL4/TL5 traffic."""
    elapsed = time.time() - state["sub2ModeStartTime"]

    # Keep Tunnel Ave stopped until both safety conditions are true:
    # 1. PL1/PL2 has flashed red for at least 2 seconds.
    # 2. TL6 has completed its green/yellow/red sequence and is fully red.
    TL4_red()
    TL5_red()

    if elapsed < PED_FLASH_TIME:
        return

    if sub3_mode != "RED_IDLE":
        if not state["sub2WaitingForTL6RedPrinted"]:
            print("[SUB2] Waiting for TL6 to turn RED before TL4/TL5 resume")
            state["sub2WaitingForTL6RedPrinted"] = True
        return

    PL12_stop_flash_red()
    TL4_green()
    TL5_red()
    state["sub2EmergencyStartTime"] = 0.0
    state["sub2EmergencyQueuedPrinted"] = False
    print("[SUB2] TL6 is RED. Emergency response done - normal cycle resumes")
    enter_mode(MODE_TL4_GREEN)


def check_buttons():
    """Read PB1/PB2 and queue one pedestrian request per press."""
    pb1_reading = board.digital_read(PB1_PIN)
    pb2_reading = board.digital_read(PB2_PIN)

    pb1_value = 1
    pb2_value = 1

    if pb1_reading is not None and pb1_reading[0] is not None:
        pb1_value = pb1_reading[0]

    if pb2_reading is not None and pb2_reading[0] is not None:
        pb2_value = pb2_reading[0]

    # The supplied Sub2 standalone uses active-low buttons.
    pb1_pressed = pb1_value == 0
    pb2_pressed = pb2_value == 0
    pressed_now = pb1_pressed or pb2_pressed

    was_pressed = state["sub2PBwasPressed"]

    if pressed_now and not was_pressed:
        request_already_active = (
            state["sub2PedRequestPending"]
            or state["sub2Mode"] in (MODE_PED_WAIT, MODE_PED_WALK, MODE_PED_FLASH)
            or (
                state["sub2Mode"] == MODE_YELLOW
                and state["sub2YellowAfter"] == MODE_PED_WALK
            )
        )

        if not state["sub2Lockout"] and not request_already_active:
            if pb1_pressed:
                print("[SUB2] Pedestrian request received from PB1")
            else:
                print("[SUB2] Pedestrian request received from PB2")
            state["sub2PedRequestPending"] = True
            state["sub2PedRequestTime"] = time.time()

    state["sub2PBwasPressed"] = pressed_now


def update_lockout():
    """Clear the 30 second pedestrian lockout when it expires."""
    if state["sub2Lockout"]:
        if time.time() - state["sub2LockoutStartTime"] >= PED_LOCKOUT:
            state["sub2Lockout"] = False
            print("[SUB2] Pedestrian lockout finished")


def update_pending_pedestrian_yellow_request():
    """If PB1/PB2 was pressed during yellow, finish that yellow then walk."""
    if not state["sub2PedRequestPending"]:
        return

    if state["sub2Mode"] != MODE_YELLOW:
        return

    if state["sub2YellowAfter"] == MODE_EMERG_HOLD:
        return

    if time.time() - state["sub2PedRequestTime"] >= PED_WAIT:
        state["sub2YellowAfter"] = MODE_PED_WALK


def sub2_traffic_is_stopped():
    """Return True once TL4/TL5 are red and the 3.I1 minimum delay has passed."""
    if state["sub2Mode"] != MODE_EMERG_HOLD:
        return False

    if state["sub2EmergencyStartTime"] == 0.0:
        return False

    return time.time() - state["sub2EmergencyStartTime"] >= MINIMUM_TL6_RELEASE_DELAY


def sub2_update():
    """Run one update of Subsystem 2."""
    update_lockout()

    if (
        not state["sub2OverheightDetected"]
        and state["sub2Mode"] in (MODE_TL4_GREEN, MODE_TL5_GREEN)
    ):
        state["sub2EmergencyStartTime"] = 0.0
        state["sub2EmergencyQueuedPrinted"] = False

    # Pedestrian buttons are ignored while the overheight override is active.
    if not state["sub2OverheightDetected"]:
        check_buttons()
    else:
        state["sub2PedRequestPending"] = False

    update_pending_pedestrian_yellow_request()

    if state["sub2OverheightDetected"]:
        mode = state["sub2Mode"]
        if mode == MODE_EMERG_FLASH:
            PL12_stop_flash_red()
            PL12_green_on()
            enter_mode(MODE_EMERG_HOLD)
        elif mode not in (MODE_YELLOW, MODE_EMERG_HOLD, MODE_EMERG_FLASH):
            start_emergency()
        elif mode == MODE_YELLOW:
            if state["sub2EmergencyStartTime"] == 0.0:
                state["sub2EmergencyStartTime"] = time.time()
            if not state["sub2EmergencyQueuedPrinted"]:
                print("[SUB2] OVERHEIGHT detected - waiting for current yellow to finish")
                state["sub2EmergencyQueuedPrinted"] = True
            state["sub2PedRequestPending"] = False
            state["sub2YellowAfter"] = MODE_EMERG_HOLD

    mode = state["sub2Mode"]

    if mode == MODE_TL4_GREEN:
        do_TL4_green()
    elif mode == MODE_TL5_GREEN:
        do_TL5_green()
    elif mode == MODE_YELLOW:
        do_yellow()
    elif mode == MODE_PED_WAIT:
        do_ped_wait()
    elif mode == MODE_PED_WALK:
        do_ped_walk()
    elif mode == MODE_PED_FLASH:
        do_ped_flash()
    elif mode == MODE_EMERG_HOLD:
        do_emerg_hold()
    elif mode == MODE_EMERG_FLASH:
        do_emerg_flash()


# ============================================================
# Subsystem 3 state machine
# ============================================================

def get_tl6_green_time(ds1_night):
    """Return TL6 green time: 5 seconds by day, 10 seconds by night."""
    if ds1_night == 1:
        return NIGHT_GREEN_SECONDS

    return DAY_GREEN_SECONDS


def start_tl6_green(ds1_night, filtered_distance):
    """Start the TL6 green stage after Subsystem 2 is safely stopped."""
    global sub3_mode
    global sub3_mode_start_time
    global sub3_green_time

    sub3_green_time = get_tl6_green_time(ds1_night)
    set_tl6_green()
    sub3_mode = "GREEN_MINIMUM"
    sub3_mode_start_time = time.time()

    if filtered_distance is not None:
        print("[SUB3] US5 detected vehicle at", round(filtered_distance, 2), "cm")

    if ds1_night == 1:
        print("[SUB3] TL6 GREEN for at least 10 seconds because DS1 is night")
    else:
        print("[SUB3] TL6 GREEN for at least 5 seconds")


def sub3_update(us5_present, filtered_distance, ds1_night):
    """Run one update of Subsystem 3 without blocking Subsystem 2."""
    global sub3_mode
    global sub3_mode_start_time

    # 3.G3: floodlights stay on only while US5 detects a vehicle at night.
    set_floodlights(us5_present == 1 and ds1_night == 1)

    if sub3_mode == "RED_IDLE":
        set_tl6_red()

        if us5_present == 1:
            sub3_mode = "WAITING_FOR_SUB2"
            sub3_mode_start_time = time.time()
            print("[SUB3] 3.I1: waiting for TL4/TL5 to turn red")

    elif sub3_mode == "WAITING_FOR_SUB2":
        set_tl6_red()

        if us5_present == 0:
            sub3_mode = "RED_IDLE"
            print("[SUB3] US5 cleared before TL6 green")
        elif sub2_traffic_is_stopped():
            start_tl6_green(ds1_night, filtered_distance)

    elif sub3_mode == "GREEN_MINIMUM":
        set_tl6_green()

        elapsed = time.time() - sub3_mode_start_time

        if elapsed >= sub3_green_time:
            if us5_present == 1:
                sub3_mode = "GREEN_HOLD"
                print("[SUB3] 3.R2: TL6 holding solid GREEN until US5 clears")
            else:
                set_tl6_yellow()
                sub3_mode = "YELLOW"
                sub3_mode_start_time = time.time()
                print("[SUB3] TL6 -> YELLOW for 3 seconds")

    elif sub3_mode == "GREEN_HOLD":
        set_tl6_green()

        if us5_present == 0:
            set_tl6_yellow()
            sub3_mode = "YELLOW"
            sub3_mode_start_time = time.time()
            print("[SUB3] US5 clear. TL6 -> YELLOW for 3 seconds")

    elif sub3_mode == "YELLOW":
        set_tl6_yellow()

        elapsed = time.time() - sub3_mode_start_time

        if elapsed >= TL6_YELLOW_SECONDS:
            set_tl6_red()
            sub3_mode = "RED_IDLE"
            print("[SUB3] TL6 -> RED")


# ============================================================
# Main loop
# ============================================================

def main():
    """Main integrated controller loop."""
    global last_us5_present

    setup_board()

    try:
        while True:
            read_daylight()

            filtered_distance = read_us5_filtered_distance()
            us5_present = calculate_us5_presence(last_us5_present, filtered_distance)

            ds1_night, ds1_value = read_ds1_state(us5_present)
            log_ds1_change(ds1_night, ds1_value)

            if us5_present != last_us5_present:
                if us5_present == 1:
                    print("[US5] Overheight vehicle detected")
                else:
                    print("[US5] Overheight vehicle cleared")
                    us5_samples.clear()

            state["sub2OverheightDetected"] = bool(us5_present)

            sub2_update()
            sub3_update(us5_present, filtered_distance, ds1_night)

            PL12_red_update()
            shift_out_bits()

            last_us5_present = us5_present
            time.sleep(POLL_DELAY_SECONDS)

    except KeyboardInterrupt:
        print("\nKeyboardInterrupt received. Shutting down integrated controller.")
    finally:
        shutdown_system()


if __name__ == "__main__":
    main()
