"""
ENG1013 Traffic System Project
Integrated implementation for Subsystem 2 and Subsystem 3.

Subsystem 2 chosen features:
    2.R1 - PB1/PB2 trigger the pedestrian sequence.
    2.R2 - Print each accepted pedestrian request once.
    2.R3 - TL4/TL5 run a normal 20s/10s cycle.
    2.G1 - Hardware-debounced buttons and 30s lockout after a request.
    2.G2 - PL1/PL2 red flashing is generated by a hardware NE556 timer.
    2.G3 - DS2 changes TL4/TL5 timings at night.
    2.I1 - US5 forces TL4/TL5 red and PL1/PL2 green.

Subsystem 3 chosen features:
    3.R1 - US5 triggers TL6 green, yellow, red.
    3.R2 - TL6 stays green while US5 still detects the vehicle.
    3.G2 - US5 readings are filtered using a moving average.
    3.G3 - DS1 turns FL1/FL2 on at night while US5 detects a vehicle.
    3.G4 - DS1 changes TL6 green time from 5s to 10s at night.
    3.I1 - TL6 waits at least 3s for TL4/TL5 to become red first.

Not implemented:
    3.G1 - TL6 green flashing with a 555 timer is intentionally excluded.
"""

from pymata4 import pymata4
import time


# ---------------------------------------------------------------------------
# Arduino direct pins
# ---------------------------------------------------------------------------

# One 74HC595 shift register is used for TL4/TL5 and pedestrian solid outputs.
shiftDataPin = 2
shiftLatchPin = 3
shiftClockPin = 4

# PB1/PB2 are wired active-high with hardware debounce.
pb1Pin = 5
pb2Pin = 6

# US5 is shared by subsystem 2 integration and subsystem 3 exit control.
us5TriggerPin = 7
us5EchoPin = 8

# TL6 and the floodlights are driven directly by Arduino pins.
tl6RedPin = 9
tl6YellowPin = 10
tl6GreenPin = 11
floodlightPin = 12

# This enables the NE556 reset pin for PL1/PL2 flashing red.
plFlashEnablePin = 13

# DS2 controls subsystem 2 day/night timing. DS1 controls subsystem 3 lighting.
ds2AnalogPin = 0
ds1AnalogPin = 1


# ---------------------------------------------------------------------------
# 74HC595 output map
# ---------------------------------------------------------------------------

tl4RedOutput = 0
tl4YellowOutput = 1
tl4GreenOutput = 2
tl5RedOutput = 3
tl5YellowOutput = 4
tl5GreenOutput = 5
plRedSolidOutput = 6
plGreenOutput = 7


# ---------------------------------------------------------------------------
# Calibration values
# ---------------------------------------------------------------------------

# US5 presence detection. Adjust these after testing your model.
us5TriggerDistanceCm = 15.0
us5ClearDistanceCm = 18.0
us5MaxValidDistanceCm = 300.0
us5MovingAverageWindow = 5

# With the wiring guide's LDR dividers, darker light gives a lower analog value.
ds2NightThreshold = 600
ds1NightThreshold = 600


# ---------------------------------------------------------------------------
# Timing values
# ---------------------------------------------------------------------------

tl4GreenDaySeconds = 20.0
tl4GreenNightSeconds = 30.0
tl5GreenDaySeconds = 10.0
tl5GreenNightSeconds = 5.0
tl4Tl5YellowSeconds = 3.0

pedestrianStartDelaySeconds = 2.0
pedestrianGreenSeconds = 3.0
pedestrianFlashRedSeconds = 2.0
pedestrianLockoutSeconds = 30.0

tl6GreenDaySeconds = 5.0
tl6GreenNightSeconds = 10.0
tl6YellowSeconds = 3.0
tl6MinimumIntegrationDelaySeconds = 3.0

loopDelaySeconds = 0.05


# ---------------------------------------------------------------------------
# Global runtime state
# ---------------------------------------------------------------------------

board = None
shiftRegisterState = [0] * 8

us5Samples = []
us5WasPresent = 0

tl4Colour = "green"
tl5Colour = "red"

subsystem2CycleState = "tl4Green"
subsystem2CycleEndTime = 0.0
subsystem2IntegrationState = "idle"
subsystem2IntegrationEndTime = 0.0

pedestrianState = "idle"
pedestrianEndTime = 0.0
pedestrianRoadToStop = ""
pedestrianLockoutUntil = 0.0
lastButtonPressed = 0

subsystem3State = "redIdle"
subsystem3StateStartTime = 0.0
subsystem3GreenSeconds = tl6GreenDaySeconds

lastDs2NightState = -1
lastDs1NightState = -1


def setup_board():
    """
    Connect to the Arduino and set up every pin used by subsystems 2 and 3.
    """
    global board

    board = pymata4.Pymata4()

    board.set_pin_mode_digital_output(shiftDataPin)
    board.set_pin_mode_digital_output(shiftLatchPin)
    board.set_pin_mode_digital_output(shiftClockPin)

    board.set_pin_mode_digital_input(pb1Pin)
    board.set_pin_mode_digital_input(pb2Pin)

    board.set_pin_mode_sonar(us5TriggerPin, us5EchoPin)

    board.set_pin_mode_digital_output(tl6RedPin)
    board.set_pin_mode_digital_output(tl6YellowPin)
    board.set_pin_mode_digital_output(tl6GreenPin)
    board.set_pin_mode_digital_output(floodlightPin)
    board.set_pin_mode_digital_output(plFlashEnablePin)

    board.set_pin_mode_analog_input(ds2AnalogPin)
    board.set_pin_mode_analog_input(ds1AnalogPin)

    time.sleep(1.0)

    all_outputs_off()
    initialise_default_states()


def write_shift_register():
    """
    Send the eight subsystem 2 output values to the 74HC595.
    """
    board.digital_write(shiftLatchPin, 0)

    # Send Q7 first and Q0 last so output index 0 maps to Q0.
    for bitNumber in range(7, -1, -1):
        board.digital_write(shiftClockPin, 0)
        board.digital_write(shiftDataPin, shiftRegisterState[bitNumber])
        board.digital_write(shiftClockPin, 1)

    board.digital_write(shiftLatchPin, 1)


def set_shift_outputs(outputPairs):
    """
    Update one or more shift-register outputs.
    """
    changed = 0

    for outputIndex, value in outputPairs:
        newValue = 1 if value else 0

        if shiftRegisterState[outputIndex] != newValue:
            shiftRegisterState[outputIndex] = newValue
            changed = 1

    if changed == 1:
        write_shift_register()


def set_tl4_colour(colour):
    """
    Set TL4 to exactly one colour.
    """
    global tl4Colour

    set_shift_outputs([
        (tl4RedOutput, colour == "red"),
        (tl4YellowOutput, colour == "yellow"),
        (tl4GreenOutput, colour == "green"),
    ])
    tl4Colour = colour


def set_tl5_colour(colour):
    """
    Set TL5 to exactly one colour.
    """
    global tl5Colour

    set_shift_outputs([
        (tl5RedOutput, colour == "red"),
        (tl5YellowOutput, colour == "yellow"),
        (tl5GreenOutput, colour == "green"),
    ])
    tl5Colour = colour


def set_pedestrian_solid_red():
    """
    Set PL1/PL2 to solid red and disable the NE556 flashing output.
    """
    set_shift_outputs([
        (plRedSolidOutput, 1),
        (plGreenOutput, 0),
    ])
    board.digital_write(plFlashEnablePin, 0)


def set_pedestrian_green():
    """
    Set PL1/PL2 to green.
    """
    set_shift_outputs([
        (plRedSolidOutput, 0),
        (plGreenOutput, 1),
    ])
    board.digital_write(plFlashEnablePin, 0)


def set_pedestrian_flashing_red():
    """
    Enable the NE556 timer so PL1/PL2 flash red for 2.G2.
    """
    set_shift_outputs([
        (plRedSolidOutput, 0),
        (plGreenOutput, 0),
    ])
    board.digital_write(plFlashEnablePin, 1)


def set_tl6_colour(colour):
    """
    Set TL6 to exactly one colour.
    """
    board.digital_write(tl6RedPin, 1 if colour == "red" else 0)
    board.digital_write(tl6YellowPin, 1 if colour == "yellow" else 0)
    board.digital_write(tl6GreenPin, 1 if colour == "green" else 0)


def set_floodlights(onState):
    """
    Turn FL1 and FL2 on or off together from one Arduino pin.
    """
    board.digital_write(floodlightPin, 1 if onState else 0)


def all_outputs_off():
    """
    Turn every output off.
    """
    for outputIndex in range(8):
        shiftRegisterState[outputIndex] = 0

    write_shift_register()
    board.digital_write(tl6RedPin, 0)
    board.digital_write(tl6YellowPin, 0)
    board.digital_write(tl6GreenPin, 0)
    board.digital_write(floodlightPin, 0)
    board.digital_write(plFlashEnablePin, 0)


def initialise_default_states():
    """
    Put subsystem 2 and subsystem 3 into their normal starting states.
    """
    global subsystem2CycleState
    global subsystem2CycleEndTime

    set_pedestrian_solid_red()
    set_tl6_colour("red")
    set_floodlights(0)

    isDs2Night, ldrValue = read_ldr_state(ds2AnalogPin, ds2NightThreshold)
    start_subsystem2_cycle_state("tl4Green", time.time(), isDs2Night)
    subsystem2CycleState = "tl4Green"

    print("Integrated subsystem 2 + 3 started.")
    print("US5 trigger threshold:", us5TriggerDistanceCm, "cm")
    print("US5 clear threshold:", us5ClearDistanceCm, "cm")
    print("DS2 initial A0:", ldrValue)
    print("3.G1 is intentionally not included.")
    print("Press Ctrl+C to stop cleanly.")


def read_ldr_state(analogPin, nightThreshold):
    """
    Read an LDR divider. Return 1 for night and 0 for day.
    """
    reading = board.analog_read(analogPin)

    if reading is None or reading[0] is None:
        return 0, 0

    ldrValue = reading[0]

    if ldrValue <= nightThreshold:
        return 1, ldrValue

    return 0, ldrValue


def log_ldr_changes(ds2Night, ds2Value, ds1Night, ds1Value):
    """
    Print day/night changes only when they change, avoiding console spam.
    """
    global lastDs2NightState
    global lastDs1NightState

    if ds2Night != lastDs2NightState:
        if ds2Night == 1:
            print("2.G3: DS2 NIGHT mode. A0 =", ds2Value)
        else:
            print("2.G3: DS2 DAY mode. A0 =", ds2Value)

        lastDs2NightState = ds2Night

    if ds1Night != lastDs1NightState:
        if ds1Night == 1:
            print("3.G3/3.G4: DS1 NIGHT mode. A1 =", ds1Value)
        else:
            print("3.G3/3.G4: DS1 DAY mode. A1 =", ds1Value)

        lastDs1NightState = ds1Night


def read_us5_filtered_distance():
    """
    Read US5 and return a moving average distance in centimetres.
    """
    reading = board.sonar_read(us5TriggerPin)

    if reading is None or reading[0] is None:
        return None

    distanceCm = reading[0]

    if distanceCm <= 0 or distanceCm > us5MaxValidDistanceCm:
        return None

    us5Samples.append(distanceCm)

    if len(us5Samples) > us5MovingAverageWindow:
        us5Samples.pop(0)

    total = 0.0
    count = 0

    for sample in us5Samples:
        total = total + sample
        count = count + 1

    if count == 0:
        return None

    return total / count


def update_us5_presence(wasPresent, distanceCm):
    """
    Convert the filtered US5 distance into a stable present/clear state.
    """
    if distanceCm is None:
        return 0

    if wasPresent == 1:
        if distanceCm <= us5ClearDistanceCm:
            return 1
        return 0

    if distanceCm <= us5TriggerDistanceCm:
        return 1

    return 0


def get_tl4_green_seconds(ds2Night):
    """
    Return TL4 green duration for day or night mode.
    """
    if ds2Night == 1:
        return tl4GreenNightSeconds

    return tl4GreenDaySeconds


def get_tl5_green_seconds(ds2Night):
    """
    Return TL5 green duration for day or night mode.
    """
    if ds2Night == 1:
        return tl5GreenNightSeconds

    return tl5GreenDaySeconds


def start_subsystem2_cycle_state(newState, now, ds2Night):
    """
    Start one state of the normal TL4/TL5 2.R3 cycle.
    """
    global subsystem2CycleState
    global subsystem2CycleEndTime

    subsystem2CycleState = newState

    if newState == "tl4Green":
        set_tl4_colour("green")
        set_tl5_colour("red")
        subsystem2CycleEndTime = now + get_tl4_green_seconds(ds2Night)
    elif newState == "tl4Yellow":
        set_tl4_colour("yellow")
        set_tl5_colour("red")
        subsystem2CycleEndTime = now + tl4Tl5YellowSeconds
    elif newState == "tl5Green":
        set_tl4_colour("red")
        set_tl5_colour("green")
        subsystem2CycleEndTime = now + get_tl5_green_seconds(ds2Night)
    elif newState == "tl5Yellow":
        set_tl4_colour("red")
        set_tl5_colour("yellow")
        subsystem2CycleEndTime = now + tl4Tl5YellowSeconds


def update_subsystem2_normal_cycle(now, ds2Night):
    """
    Continue the TL4/TL5 normal cycle when no override is active.
    """
    if now < subsystem2CycleEndTime:
        return

    if subsystem2CycleState == "tl4Green":
        start_subsystem2_cycle_state("tl4Yellow", now, ds2Night)
    elif subsystem2CycleState == "tl4Yellow":
        start_subsystem2_cycle_state("tl5Green", now, ds2Night)
    elif subsystem2CycleState == "tl5Green":
        start_subsystem2_cycle_state("tl5Yellow", now, ds2Night)
    elif subsystem2CycleState == "tl5Yellow":
        start_subsystem2_cycle_state("tl4Green", now, ds2Night)


def read_button_pressed():
    """
    Read PB1/PB2. A pressed button reads HIGH because pulldowns are used.
    """
    pb1Reading = board.digital_read(pb1Pin)
    pb2Reading = board.digital_read(pb2Pin)

    pb1Value = 0
    pb2Value = 0

    if pb1Reading is not None and pb1Reading[0] is not None:
        pb1Value = pb1Reading[0]

    if pb2Reading is not None and pb2Reading[0] is not None:
        pb2Value = pb2Reading[0]

    if pb1Value == 1 or pb2Value == 1:
        return 1

    return 0


def start_pedestrian_sequence(now):
    """
    Accept one pedestrian request and start the 2 second wait.
    """
    global pedestrianState
    global pedestrianEndTime

    pedestrianState = "waitBeforeRoadStop"
    pedestrianEndTime = now + pedestrianStartDelaySeconds
    print("2.R2: pedestrian request accepted. Sequence starts after 2 seconds.")


def update_pedestrian_button(now):
    """
    Start a pedestrian sequence only on a new button press and outside lockout.
    """
    global lastButtonPressed

    buttonPressed = read_button_pressed()

    if buttonPressed == 1 and lastButtonPressed == 0:
        if pedestrianState == "idle" and now >= pedestrianLockoutUntil:
            start_pedestrian_sequence(now)
        elif now < pedestrianLockoutUntil:
            remainingSeconds = int(pedestrianLockoutUntil - now)
            print("2.G1: pedestrian request ignored during lockout. Remaining:", remainingSeconds, "s")

    lastButtonPressed = buttonPressed


def update_pedestrian_sequence(now, ds2Night):
    """
    Continue the 2.R1 pedestrian sequence without blocking the whole program.
    """
    global pedestrianState
    global pedestrianEndTime
    global pedestrianRoadToStop
    global pedestrianLockoutUntil

    if pedestrianState == "idle" or now < pedestrianEndTime:
        return

    if pedestrianState == "waitBeforeRoadStop":
        if tl5Colour != "red":
            pedestrianRoadToStop = "tl5"
            set_tl5_colour("yellow")
            print("2.R1: TL5 -> YELLOW for 3 seconds")
        else:
            pedestrianRoadToStop = "tl4"
            set_tl4_colour("yellow")
            print("2.R1: TL4 -> YELLOW for 3 seconds")

        pedestrianState = "roadYellow"
        pedestrianEndTime = now + tl4Tl5YellowSeconds

    elif pedestrianState == "roadYellow":
        set_tl4_colour("red")
        set_tl5_colour("red")
        set_pedestrian_green()
        pedestrianState = "pedestrianGreen"
        pedestrianEndTime = now + pedestrianGreenSeconds
        print("2.R1: PL1/PL2 -> GREEN for 3 seconds")

    elif pedestrianState == "pedestrianGreen":
        set_pedestrian_flashing_red()
        pedestrianState = "pedestrianFlashRed"
        pedestrianEndTime = now + pedestrianFlashRedSeconds
        print("2.G2: PL1/PL2 -> FLASHING RED from NE556 for 2 seconds")

    elif pedestrianState == "pedestrianFlashRed":
        set_pedestrian_solid_red()
        start_subsystem2_cycle_state("tl4Green", now, ds2Night)
        pedestrianLockoutUntil = now + pedestrianLockoutSeconds
        pedestrianState = "idle"
        print("2.R1: PL1/PL2 -> SOLID RED. TL4 -> GREEN.")
        print("2.G1: 30 second pedestrian lockout started.")


def start_subsystem2_integration(now):
    """
    Start 2.I1 and the 3.I1 delay when US5 detects a vehicle.
    """
    global pedestrianState
    global subsystem2IntegrationState
    global subsystem2IntegrationEndTime

    pedestrianState = "idle"
    set_pedestrian_solid_red()

    if tl4Colour != "red":
        set_tl4_colour("yellow")

    if tl5Colour != "red":
        set_tl5_colour("yellow")

    subsystem2IntegrationState = "stoppingTraffic"
    subsystem2IntegrationEndTime = now + tl6MinimumIntegrationDelaySeconds
    print("2.I1/3.I1: US5 detected vehicle. TL4/TL5 stopping before TL6 green.")


def update_subsystem2_integration(now, us5Present, ds2Night):
    """
    Continue the 2.I1 override while US5 detects the exit vehicle.
    """
    global subsystem2IntegrationState
    global subsystem2IntegrationEndTime

    if subsystem2IntegrationState == "idle":
        return

    if subsystem2IntegrationState == "stoppingTraffic":
        if now < subsystem2IntegrationEndTime:
            return

        set_tl4_colour("red")
        set_tl5_colour("red")
        set_pedestrian_green()
        subsystem2IntegrationState = "vehiclePresent"
        print("2.I1: TL4/TL5 -> RED. PL1/PL2 -> GREEN while US5 detects vehicle.")

    elif subsystem2IntegrationState == "vehiclePresent":
        set_tl4_colour("red")
        set_tl5_colour("red")
        set_pedestrian_green()

        if us5Present == 0:
            set_pedestrian_flashing_red()
            subsystem2IntegrationState = "pedestrianFlashRed"
            subsystem2IntegrationEndTime = now + pedestrianFlashRedSeconds
            print("2.I1: US5 clear. PL1/PL2 -> FLASHING RED for 2 seconds.")

    elif subsystem2IntegrationState == "pedestrianFlashRed":
        if now < subsystem2IntegrationEndTime:
            return

        set_pedestrian_solid_red()
        start_subsystem2_cycle_state("tl4Green", now, ds2Night)
        subsystem2IntegrationState = "idle"
        print("2.I1: PL1/PL2 -> SOLID RED. Normal TL4/TL5 cycle resumed.")


def subsystem2_ready_for_tl6():
    """
    Return True once 2.I1 has made TL4/TL5 red and PL1/PL2 green.
    """
    if subsystem2IntegrationState == "vehiclePresent":
        return True

    return False


def update_subsystem2(now, us5Present, ds2Night):
    """
    Run subsystem 2: normal cycle, pedestrian buttons, and US5 override.
    """
    if us5Present == 1 and subsystem2IntegrationState == "idle":
        start_subsystem2_integration(now)

    if subsystem2IntegrationState != "idle":
        update_subsystem2_integration(now, us5Present, ds2Night)
        return

    update_pedestrian_button(now)

    if pedestrianState != "idle":
        update_pedestrian_sequence(now, ds2Night)
        return

    update_subsystem2_normal_cycle(now, ds2Night)


def get_tl6_green_seconds(ds1Night):
    """
    Return TL6 green time for day or night mode.
    """
    if ds1Night == 1:
        return tl6GreenNightSeconds

    return tl6GreenDaySeconds


def start_tl6_green(now, ds1Night):
    """
    Start TL6 green after subsystem 2 has safely stopped TL4/TL5.
    """
    global subsystem3State
    global subsystem3StateStartTime
    global subsystem3GreenSeconds

    subsystem3GreenSeconds = get_tl6_green_seconds(ds1Night)
    set_tl6_colour("green")
    subsystem3State = "greenMinimum"
    subsystem3StateStartTime = now
    print("3.R1/3.I1: TL6 -> GREEN for at least", int(subsystem3GreenSeconds), "seconds")


def update_subsystem3(now, us5Present, ds1Night):
    """
    Run subsystem 3: TL6 sequence, floodlights and the 3.I1 delay.
    """
    global subsystem3State
    global subsystem3StateStartTime

    # 3.G3: floodlights are on only at night while US5 detects a vehicle.
    set_floodlights(us5Present == 1 and ds1Night == 1)

    if subsystem3State == "redIdle":
        set_tl6_colour("red")

        if us5Present == 1:
            subsystem3State = "waitingForTunnelRed"
            subsystem3StateStartTime = now
            print("3.I1: TL6 waiting for TL4/TL5 to turn red.")

    elif subsystem3State == "waitingForTunnelRed":
        set_tl6_colour("red")

        if us5Present == 0:
            subsystem3State = "redIdle"
            print("3.I1: US5 cleared before TL6 green. TL6 remains RED.")
        elif subsystem2_ready_for_tl6():
            start_tl6_green(now, ds1Night)

    elif subsystem3State == "greenMinimum":
        set_tl6_colour("green")

        if now - subsystem3StateStartTime >= subsystem3GreenSeconds:
            if us5Present == 1:
                subsystem3State = "greenHold"
                print("3.R2: TL6 holding GREEN until US5 clears.")
            else:
                set_tl6_colour("yellow")
                subsystem3State = "yellow"
                subsystem3StateStartTime = now
                print("3.R1: TL6 -> YELLOW for 3 seconds")

    elif subsystem3State == "greenHold":
        set_tl6_colour("green")

        if us5Present == 0:
            set_tl6_colour("yellow")
            subsystem3State = "yellow"
            subsystem3StateStartTime = now
            print("3.R1: US5 clear. TL6 -> YELLOW for 3 seconds")

    elif subsystem3State == "yellow":
        set_tl6_colour("yellow")

        if now - subsystem3StateStartTime >= tl6YellowSeconds:
            set_tl6_colour("red")
            subsystem3State = "redIdle"
            print("3.R1: TL6 -> RED")


def shutdown_system():
    """
    Turn off all outputs and close the Arduino connection.
    """
    global board

    if board is None:
        return

    all_outputs_off()
    time.sleep(0.2)
    board.shutdown()
    board = None


def main():
    """
    Main loop for the integrated subsystem 2 + 3 controller.
    """
    global us5WasPresent

    setup_board()

    try:
        while True:
            now = time.time()

            ds2Night, ds2Value = read_ldr_state(ds2AnalogPin, ds2NightThreshold)
            ds1Night, ds1Value = read_ldr_state(ds1AnalogPin, ds1NightThreshold)
            log_ldr_changes(ds2Night, ds2Value, ds1Night, ds1Value)

            us5DistanceCm = read_us5_filtered_distance()
            us5Present = update_us5_presence(us5WasPresent, us5DistanceCm)

            if us5Present != us5WasPresent:
                if us5Present == 1:
                    print("US5 detected vehicle at", round(us5DistanceCm, 2), "cm.")
                else:
                    print("US5 clear.")

            us5WasPresent = us5Present

            update_subsystem2(now, us5Present, ds2Night)
            update_subsystem3(now, us5Present, ds1Night)

            time.sleep(loopDelaySeconds)

    except KeyboardInterrupt:
        print("\nKeyboardInterrupt received. Shutting down subsystem 2 + 3 integration.")
    finally:
        shutdown_system()


if __name__ == "__main__":
    main()
